Added WS2812 RGB Rotary Encoder Led for LilyGO T-embed CC1101
BruceDevices/firmware pull request #428
Opened 2024-11-16 01:40 UTC by JorgMuskens

**Proposed Changes**
The LEDs on the rotary encoder specific to the Lilygo T-Embed CC1101 can now be configured through the settings menu.

**Types of Changes**
Added functionality for WS2812 LEDs.

**Verification**
Added a couple of files to the core directory and made minor edits to other files. Efforts were made to maintain a clean and consistent structure.

**Testing**
Tested on my personal device, and it works as intended. Further code enhancements are possible, and dimming functionality for the LEDs is not yet implemented.

**Linked Issues**
None.

**User-Facing Change**
None.

**Further Comments**
Error: Cannot compute -> Eaten by shark!!!

2024-11-16 02:26 UTC, rennancockles commented
Please update your branch with latest code from main branch. This PR is reverting a lot of the changes that it wasn't supposed to revert.

2024-11-16 03:01 UTC, bmorcelli requested changes
Adding things is good, but it is reverting many improvements added in /ports/devices/interface.h/cpp

2024-11-16 03:01 UTC, bmorcelli commented on platformio.ini
This won't be accepted, this platformio.ini must be used for global project only.

keep device related libs and environments in their own /ports/devices/platformio.ini

2024-11-16 03:01 UTC, bmorcelli commented on src/core/menu_items/OthersMenu.cpp
This file must keep the HAS_KEYBOARD_HID flag, not CARDPUTER

2024-11-16 03:01 UTC, bmorcelli commented on src/main.cpp
rebase this file, and add only the things you need.. it is bringing back _setup_gpio() from devices interfaces

2024-11-21 18:20 UTC, pr3y commented
Closed due to inactivity

2024-11-21 18:20 UTC, closed without merging