feat: Add Reverse Shell feature with web interface and menu integration
BruceDevices/firmware pull request #512
Opened 2024-12-03 21:03 UTC by 9dl

#### Proposed Changes ####  
Reverse Shell feature with Web Interface for controlling and executing commands remotely through BruceC2.

#### Types of Changes ####  
- New Feature

#### Verification ####  
- Verify that the reverse shell connects to the machine and allows for remote execution of commands via the BruceC2 interface.
- Ensure the web interface works at `http://192.168.4.1` and displays the status and interaction controls.

#### Testing ####  
- Not covered by existing unit tests.
- Consider adding integration tests to ensure the connection and command execution work properly across different platforms.

#### Linked Issues ####  
- N/A (If there are any related issues, they can be linked here)

#### User-Facing Change ####  
```release-note
- Introduced a Reverse Shell feature with web interface for remote command execution via BruceC2.
- Provides TCP-based shell access to a machine and a web interface to manage commands.
```

#### Further Comments ####  
- To execute, start **Reverse Shell Mode** in Bruce and wait for BruceC2 to establish the connection.
- It’s recommended to use **BadUSB scripts** to automate the execution of BruceC2 on the target machine.

```cpp// Developed by Fourier (github.com/9dl)
// Use BruceC2 to interact with the reverse shell server
// BruceC2: https://github.com/9dl/Bruce-C2
// To use BruceC2:
// 1. Start Reverse Shell Mode in Bruce
// 2. Start BruceC2 and wait.
// 3. Visit 192.168.4.1 in your browser to access the web interface for shell executing.

// 32bit: https://github.com/9dl/Bruce-C2/releases/download/v1.0/BruceC2_windows_386.exe
// 64bit: https://github.com/9dl/Bruce-C2/releases/download/v1.0/BruceC2_windows_amd64.exe```

2024-12-03 21:07 UTC, 9dl commented
![image](https://github.com/user-attachments/assets/b6c06892-6db4-4a88-a1de-c7244144d413)
![image](https://github.com/user-attachments/assets/242d54d7-957d-49fb-8b38-93e1ac1fd695)

2024-12-04 22:19 UTC, bmorcelli commented
Can you rebase to fix the conflicts?

2024-12-04 22:37 UTC, bmorcelli requested changes
You have all your code in the /core/menu_items files.. it is not how things work...

please creeate new set of files ( ReverseShell.h/cpp) in /modules/wifi/ and add the call for this feature into the Wifi menu.. doesn't make sense have an access to a Wifi application in the Main menu..

2024-12-05 06:30 UTC, 9dl commented
I will fix it when I'm home.

2024-12-12 05:19 UTC, bmorcelli commented on src/core/menu_items/WifiMenu.cpp
> +// 32bit: https://github.com/9dl/Bruce-C2/releases/download/v1.0/BruceC2_windows_386.exe
Please Add these files into a .zip in the ./sd_files/reverseshell folder and, if you may, add the BADUSB payload to this folder, so we can ,merge with all files set..

2024-12-12 06:10 UTC, merged